apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30083  # akses dari luar cluster: NodeIP:30083
